language: java

jdk:
- openjdk11

-addons:
  apt:
    packages:
    - libxml2-utils

before_install:
  - chmod +x mvnw
# skip the Travis-CI install phase because Maven handles that directly
install:
- "true"

script:
- "./mvnw install"